language: c
sudo: required
before_script:
  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
  - sudo apt-get install git-lfs=1.1.0
# git-lfs 1.1.0 always prompts for a password, even when anonymous access is ok
# to bypass the prompt tell git to use a dummy credentials file:
  - git config --global credential.helper 'store --file .anonymous-git-credentials'
# On travis using git-lfs 1.1.0, must prevent git lfs from writing directly to stdout.
# This is a known bug for which a fix has been merged into upstream.
# see: https://github.com/github/git-lfs/issues/880 
  - git lfs fetch > /tmp/git-lfs-fetch.log
  - cat /tmp/git-lfs-fetch.log
  - git lfs checkout > /tmp/git-lfs-checkout.log
  - cat /tmp/git-lfs-checkout.log

before_install:
  - curl -OL  https://raw.githubusercontent.com/craigcitro/r-travis/1e982113c366fff5a9595a49358fbb395b7d205d/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

script:
  - ./travis-tool.sh run_tests
  - R CMD INSTALL nardata_*.tar.gz
  - R --vanilla -e 'library(nardata);source("R/serialize_time_series.R"); serialize_time_series();'
  - DIFFERING_SERIALIZED_FILES=`git ls-files -mo inst/extdata/`
  - "[[ -n DIFFERING_SERIALIZED_FILES ]] && { echo 'Error : The following serialized files are different than what is checked in. Did you forget to serialize them or check in the results?'; echo $DIFFERING_SERIALIZED_FILES; exit 1; } || { echo 'Serialized files are identical'; }"

after_failure:
  - ./travis-tool.sh dump_logs
